name = "workers-airtable-form"
type = "javascript"

account_id = "b27a3721b5eeb228a8f5ce60a4fcf39a"
workers_dev = true

[vars]
AIRTABLE_BASE_ID = "appikq78I3OJp58vD"
AIRTABLE_TABLE_NAME = "Form Submissions"
FORM_URL = "https://workers-airtable-form.pages.dev"
